import type { NotionClientWrapper } from './client.js';

/**
 * Create a new audit page in the AI Feature Request Triage database.
 */
export async function createAuditPage(
  client: NotionClientWrapper,
  auditDatabaseId: string,
  productPageId: string,
  frCount: number,
): Promise<{ id: string; url: string }> {
  const page = await client.createPage({
    parent: { database_id: auditDatabaseId },
    icon: { type: 'emoji', emoji: '🤖' } as any,
    properties: {
      title: {
        title: [{ text: { content: 'New FR Audit' } }],
      },
      Status: {
        status: { name: 'In progress' },
      },
      'FRs Processed': {
        number: frCount,
      },
      Product: {
        relation: [{ id: productPageId }],
      },
    } as any,
    children: [
      {
        object: 'block',
        type: 'paragraph',
        paragraph: {
          rich_text: [
            { type: 'text', text: { content: 'Generated by ' } },
            {
              type: 'text',
              text: { content: 'FR Triage Service' },
              annotations: { bold: true },
              href: 'https://github.com/evanlemmons/fr-triage-service'
            },
            { type: 'text', text: { content: ' (GitHub Actions)' } },
          ],
        },
      },
    ] as any,
  });

  return { id: page.id, url: (page as any).url ?? '' };
}

/**
 * Update the FR's Product Pulse relation with merged IDs.
 */
export async function updateFRPulseRelation(
  client: NotionClientWrapper,
  frPageId: string,
  mergedPulseIds: string[],
): Promise<void> {
  await client.updatePage({
    page_id: frPageId,
    properties: {
      'Product Pulse': {
        relation: mergedPulseIds.map((id) => ({ id })),
      },
    } as any,
  });
}

/**
 * Update the FR's Ideas Database relation with merged IDs.
 */
export async function updateFRIdeaRelation(
  client: NotionClientWrapper,
  frPageId: string,
  mergedIdeaIds: string[],
): Promise<void> {
  await client.updatePage({
    page_id: frPageId,
    properties: {
      'Ideas Database': {
        relation: mergedIdeaIds.map((id) => ({ id })),
      },
    } as any,
  });
}

/**
 * Finalize the audit page: set status to Complete, add completed time.
 */
export async function finalizeAuditPage(
  client: NotionClientWrapper,
  auditPageId: string,
): Promise<void> {
  await client.updatePage({
    page_id: auditPageId,
    properties: {
      Status: {
        status: { name: 'Complete' },
      },
      'Completed time': {
        date: { start: new Date().toISOString() },
      },
    } as any,
  });
}

/**
 * Update the audit page with final status and notes.
 * Replaces finalizeAuditPage for more granular control over audit status.
 */
export async function updateAuditPageStatus(
  client: NotionClientWrapper,
  auditPageId: string,
  status: 'Complete' | 'Error' | 'Needs Attention',
  notes?: string,
): Promise<void> {
  const properties: any = {
    Status: {
      status: { name: status },
    },
    'Completed time': {
      date: { start: new Date().toISOString() },
    },
  };

  // Add Notes property if provided, with truncation to prevent exceeding Notion's 2000 char limit
  if (notes) {
    const truncatedNotes = notes.length > 1900
      ? notes.substring(0, 1900) + '...\n\n[See audit page for full details]'
      : notes;

    properties.Notes = {
      rich_text: [{ text: { content: truncatedNotes } }],
    };
  }

  await client.updatePage({
    page_id: auditPageId,
    properties,
  });
}
